namespace PokeChess.Server.Enums
{
    public enum SpellType
    {
        GainGold,
        GainMaxGold,
        BuffTargetAttack,
        BuffFriendlyTargetAttack,
        BuffTargetHealth,
        BuffFriendlyTargetHealth,
        BuffBoardAttack,
        BuffBoardHealth,
        BuffCurrentShopAttack,
        BuffCurrentShopHealth,
        BuffShopAttack,
        BuffShopHealth,
        AddKeywordToTarget,
        GetRandomMinionsFromTavern,
        GetRandomCardsFromTavern,
        GetTavern,
        GetRandomMinionByType,
        GetRandomMinionByTier,
        EvolveMinion,
        Consume,
        Discover,
        Quest,
        Secret
    }
}
